### ISSUE TITLE
Failing to get a Signed Certificate

### ISSUE THREAD

**Issue by DarylGraves** [torkildr/nginx-letsencrypt-armhf#2]
It could well be something I'm doing but I'm getting this error when running my container:

**Parsing account key...
Parsing CSR...
Registering account...
Traceback (most recent call last):
  File "/opt/acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/opt/acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/opt/acme-tiny/acme_tiny.py", line 92, in get_crt
    raise ValueError("Error registering: {0} {1}".format(code, result))
ValueError: Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
  "status": 400
}
2019-07-29T19:50:59+0000 ERROR Failed to get signed certificate for $mysite**

Is this because the agreements are out of sync? Can I amend this manually?

**Comment by DarylGraves** [comment]
Ok figured out a workaround which is working although obviously not ideal:

- Run an version of the container without any config so it's simply running in the background.
- **docker container cp $container_name:/opt/acme-tiny ./acme-tiny** - This copies the folder (with the python script) to your root machine
- Exit, stop and delete the container you made.
- On your machine, edit acme-tiny.py so the agreement is the one that matches the one in the error code (line 85 has the agreement url)

Now when you next load it up you need to include another folder (the one with your updated python file) so add this to the startup **-v $PWD/acme-tiny:/opt/acme-tiny**

I can see in the code that the acme_tiny zip file is pulled from diafygi's repository so I will raise an issue there.
